"""added methods to models

Revision ID: 2dfb7ef6c89c
Revises: eb9fd7da9ca4
Create Date: 2023-06-04 13:45:44.778514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfb7ef6c89c'
down_revision = 'eb9fd7da9ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
